version: "3.8"
services:
  database:
    restart: unless-stopped
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      # So you can use a database client on your host machine
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql
  php:
    restart: unless-stopped
    container_name: teamsbackup_php
    build:
      context: ./docker/php
#      dockerfile: ./docker/dockerfiles/PHP/Dockerfile
    working_dir: ${WEB_ROOT}
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - .:${WEB_ROOT}
      - terminal-history:/root/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - WEB_ROOT=${WEB_ROOT}
  webserver:
    restart: unless-stopped
    image: nginx:alpine
    depends_on:
      - php
    ports:
      # Exposing both http and https
      - 80:80
      - 443:443
    volumes:
      - .:${WEB_ROOT}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - WEB_ROOT=${WEB_ROOT}
  store:
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - redis-data:/data

  worker:
    restart: unless-stopped
    container_name: teamsbackup_worker
    build:
      context: ./docker/php
    #      dockerfile: ./docker/dockerfiles/PHP/Dockerfile
    working_dir: ${WEB_ROOT}
    volumes:
      - .:${WEB_ROOT}
      - terminal-history:/root/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - WEB_ROOT=${WEB_ROOT}
    command: php artisan horizon


volumes:
  terminal-history:
  redis-data:
  mysql-data:
